<a href="https://colab.research.google.com/github/Dipu1764/ML-5/blob/DATA/ML_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
data2 = {
    'feature1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'feature2': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    'target': [0, 0, 0, 1, 1, 1, 0, 0, 0, 1]
}

In [ ]:
df = pd.DataFrame(data2)
print(df)

X = df[['feature1','feature2']]
y = df['target']

   feature1  feature2  target
0         1        11       0
1         2        12       0
2         3        13       0
3         4        14       1
4         5        15       1
5         6        16       1
6         7        17       0
7         8        18       0
8         9        19       0
9        10        20       1

In [ ]:
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Initialize a list to store the scores
scores = []

# Iterate over the folds
for train_index, test_index in kf.split(X):
    # Split the data into training and test sets
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Initialize and train the model
    model = LogisticRegression()
    model.fit(X_train, y_train)

    # Perform predictions on the test set
    y_pred = model.predict(X_test)

    # Calculate the accuracy score
    score = accuracy_score(y_test, y_pred)

    # Append the score to the list
    scores.append(score)

# Calculate the average score
avg_score = sum(scores) / k

# Print the scores and average score
print("Scores:", scores)
print("Average Score:", avg_score)

Scores: [0.5, 0.5, 0.5, 0.0, 0.5]
Average Score: 0.4

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score, confusion_matrix, accuracy_score

In [ ]:
df = pd.read_csv("/content/fraudtransactions.csv")
df.head()

   Unnamed: 0  Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Fraud
0           0   1.021519  -0.548166  -2.079610   2.988799  -2.282637      0
1           1   0.210297   0.378811  -1.558116   1.737750  -2.083806      0
2           2   0.312219   0.266673  -0.873507   2.422799  -2.373239      0
3           3   0.613577  -0.487993  -1.824985   2.346751  -2.172025      0
4           4  -0.062001  -0.837709  -1.414938   1.124668  -1.826684      0

In [ ]:
print("#info", df.info)

print("#shape", df.shape)

print("#isnull", df.isnull().sum())

#info <bound method DataFrame.info of      Unnamed: 0  Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Fraud
0             0   1.021519  -0.548166  -2.079610   2.988799  -2.282637      0
1             1   0.210297   0.378811  -1.558116   1.737750  -2.083806      0
2             2   0.312219   0.266673  -0.873507   2.422799  -2.373239      0
3             3   0.613577  -0.487993  -1.824985   2.346751  -2.172025      0
4             4  -0.062001  -0.837709  -1.414938   1.124668  -1.826684      0
..          ...        ...        ...        ...        ...        ...    ...
995         995   0.141158   1.410214  -2.320817   0.749351  -1.453040      0
996         996   0.580855   0.286195  -2.667136   1.670716  -1.840654      0
997         997   0.769980  -1.460925  -3.103829   1.648837  -1.679590      0
998         998   1.133483   0.553364  -3.761090   1.939160  -1.648539      0
999         999   0.457990  -2.664332  -0.959610   2.629161  -2.386679      0

[1000 rows x 7 columns]>
#shape (1000, 7)
#isnull Unnamed: 0    0
Feature_1     0
Feature_2     0
Feature_3     0
Feature_4     0
Feature_5     0
Fraud         0
dtype: int64

In [ ]:
df['Fraud'].value_counts()

Fraud
0    990
1     10
Name: count, dtype: int64

In [ ]:
x = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [ ]:
print(f"X shape: {X.shape}, Y shape: {Y.shape}")

X shape: (10, 2), Y shape: (1000,)